[workspace]
resolver = "2"
members = [
    "steel-engine",
    "steel-common",
    "steel-editor",
    "steel-dynlib",
    "steel-client",
    "steel-server",
]
exclude = [
    "steel-project",
    "examples/test-project",
    "examples/ball",
]
