[workspace]
resolver = "2"
members = [
    "steel-engine",
    "steel-common",
    "steel-editor",
    "steel-build/steel-dynlib",
    "steel-build/steel-client",
    "steel-build/steel-server",
]
exclude = [
    "steel-build/steel-project",
    "examples/demo",
    "examples/ball",
]
