[package]
name = "steel-proc"
version = "0.1.0"
edition = "2021"
description = "The steel game engine proc-macro library."
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.60"
quote = "1.0.36"
proc-macro2 = "1.0.81"
